import {Platform, StyleSheet} from 'react-native';
import {Color, Fonts} from '../utils';

export default StyleSheet.create({
  container: {
    flex: 1,
    padding: 10,
    backgroundColor: Color.whiteColor,
  },
  item: {
    backgroundColor: '#f9c2ff',
    padding: 20,
    marginVertical: 8,
  },
  header: {
    fontFamily: Fonts.robotoRegular,
    fontSize: 21,
    color: '#47525E',
    marginLeft: 10,
  },
  title: {
    fontSize: 24,
  },
  WatchImage: {
    width: 50,
    height: 50,
    borderRadius: 50 / 2,
    overflow: 'hidden',
    color: Color.darkGreyColor,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  WatchTextBox: {
    paddingHorizontal: 10,
    width: '100%',
  },
  WatchText: {
    fontSize: 21,
    color: '#8492A6',
    paddingRight: 80,
    fontFamily: Fonts.robotoRegular,
  },
  Boxbg: {
    borderRadius: 8,
    marginVertical: 5,
    padding: 5,
    paddingBottom: 0,
    width: '100%',
  },
  WatchBox: {
    flexDirection: 'row',
  },
  Heading: {
    fontSize: 24,
    color: '#1F2D3D',
    marginBottom: 5,
    fontFamily: Fonts.robotoRegular,
  },
  WatchImgBox: {
    width: 50,
  },
  Floating: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: Color.floatingButtonColor,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: 0,
    right: 0,
    marginRight: 20,
    marginBottom: 20,
  },
  FloatingText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Color.whiteColor,
  },
  labelText: {
    fontFamily: Fonts.robotoRegular,
    fontSize: 18,
    color: '#8492A6',
  },
  textInput: {
    fontFamily: Fonts.robotoRegular,
    fontSize: 18,
    color: Color.blackColor,
    marginTop: Platform.OS === 'ios' ? 5 : 0,
    borderBottomColor: Color.underlineColor,
    borderBottomWidth: 2,
    paddingBottom: 10,
  },
  selectImageButton: {
    width: '50%',
    backgroundColor: Color.white,
    height: 50,
    marginTop: 35,
    borderWidth: 1,
    borderColor: '#FF0000',
    justifyContent: 'center',
    paddingLeft: 15,
    paddingRight: 15,
  },
  selectImageButtonText: {
    fontFamily: Fonts.robotoRegular,
    color: '#CA0017',
    textAlign: 'left',
    fontSize: 18,
  },
  loginButton: {
    width: 100,
    backgroundColor: Color.primaryColor,
    height: 50,
    borderRadius: 5,
    justifyContent: 'center',
    marginTop: 32,
    paddingLeft: 15,
    paddingRight: 15,
  },
  loginButtonText: {
    fontFamily: Fonts.robotoRegular,
    color: Color.whiteColor,
    textAlign: 'center',
    fontSize: 22,
  },
  modalContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    width: '100%',
  },
  modalView: {
    justifyContent: 'flex-start',
    width: '90%',
    height: 230,
    backgroundColor: '#EFF2F7',
    borderRadius: 8,
  },
  textStyle: {
    color: '#1F2D3D',
    textAlign: 'left',
    fontFamily: Fonts.robotoRegular,
    fontSize: 24,
    marginLeft: 36,
    marginTop: 16,
  },
  subTextStyle: {
    color: '#8492A6',
    textAlign: 'left',
    fontFamily: Fonts.robotoRegular,
    fontSize: 18,
    marginLeft: 36,
    marginTop: 23,
  },
  alertButton: {
    width: 100,
    backgroundColor: Color.primaryColor,
    height: 50,
    borderRadius: 3,
    alignSelf: 'flex-end',
    justifyContent: 'center',
    marginTop: 62,
    paddingLeft: 15,
    paddingRight: 15,
  },
  alertButtonText: {
    fontFamily: Fonts.robotoRegular,
    color: Color.whiteColor,
    textAlign: 'center',
    fontSize: 20,
  },
  imageDataText: {
    fontFamily: Fonts.robotoRegular,
    color: '#000000',
    textAlign: 'left',
    fontSize: 18,
    width: '45%',
    marginLeft: 20,
    marginTop: 45,
  },
});
